### ISSUE TITLE
No install.sh in repo

### ISSUE THREAD

**Issue by duckunix** [mentha/pixelbook-drivers#1]
The [README.md](https://github.com/mentha/pixelbook-drivers#installing) says to run `make install` which in the [Makefile](https://github.com/mentha/pixelbook-drivers/blob/5b29a4bcded25e7cd4f348036b02f3d54cce36dc/Makefile#L12) calls `./install.sh`, however there is no `install.sh` in the repo

**Comment by mentha** [comment]
Thanks for reminding me about that. `make install` should now work in the latest commit.
